import Head from 'next/head'
import Feed from '../components/Feed';
import Header from '../components/Header'
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';
import Messenger from '../components/Messenger';

export default function Home() {
	return (
		<div className="h-screen bg-gray-100 overflow-hidden">
			<Head>
				<title>Cerebro Bot Demo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className="flex">
				<Sidebar />
				<Feed />
				<Widgets />
				<Messenger />
			</main>
		</div>
	)
}